---
- name: 'Create the PowerDNS Admin database'
  mysql_db:
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ pdnsadmin_db_host | default('127.0.0.1') }}"
    login_port: "{{ pdnsadmin_db_port | default('3306') }}"
    name: "{{ pdnsadmin_db_name }}"
    state: 'present'

- name: Grant PowerDNS access to the MySQL databases
  mysql_user:
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ pdnsadmin_db_host | default('127.0.0.1') }}"
    login_port: "{{ pdnsadmin_db_port | default('3306') }}"
    name: "{{ pdnsadmin_db_user }}"
    password: "{{ pdnsadmin_db_password }}"
    host: "{{ pdnsadmin_db_host | default('127.0.0.1') }}"
    priv: "{{ pdnsadmin_db_name }}.*:ALL"
    append_privs: yes
    state: present

- name: 'Init DB'  # noqa 305
  shell: "{{ pdnsadmin_venv_path }}/flask_exec flask db init"
  args:
    creates: "{{ pdnsadmin_version_path }}/migrations"
  become: true

- name: 'Update DB'
  shell: "{{ pdnsadmin_venv_path }}/flask_exec flask db upgrade && touch {{ pdnsadmin_version_path }}/db_upgraded"
  args:
    creates: "{{ pdnsadmin_version_path }}/db_upgraded"
  notify: 'restart powerdns_admin.service'
  become: true
