---
- name: 'Add PowerDNS Admin config'
  template:
    dest: "{{ pdnsadmin_work_path }}/{{ item }}"
    group: "{{ pdnsadmin_group }}"
    mode: '660'
    owner: "{{ pdnsadmin_user }}"
    src: "{{ item }}.j2"
  loop:
    - PowerDNS_Admin_config.py
