---
- name: 'Add PowerDNS Admin config'
  loop:
    - PowerDNS_Admin_config.py
  template:
    backup: true
    dest: "{{ pdnsadmin_work_path }}/{{ item }}"
    group: "{{ pdnsadmin_group }}"
    mode: '660'
    owner: "{{ pdnsadmin_user }}"
    src: "{{ role_path }}/templates/{{ item }}.j2"
  notify: 'restart powerdns_admin.service'
  become: true

- include: configure_database.yml

- name: 'Update perms on working directory for idempotency'
  file:
    group: "{{ pdnsadmin_group }}"
    owner: "{{ pdnsadmin_user }}"
    path: "{{ pdnsadmin_work_path }}"
    recurse: true
    state: 'directory'
  become: true
