---
- name: 'Install ansible apt_* requirements'
  when: ansible_os_family == 'Debian'
  loop:
    - python3-apt
    - gpg
  package:
    name: "{{ item }}"
    state: 'present'
  become: true

- include: sources.yml

- name: 'Install system requirements'
  loop: "{{ pdnsadmin_requirements }}"
  package:
    name: "{{ item }}"
    state: 'present'
  become: true
