---
- name: 'Install ansible apt_* requirements'
  package:
    name: "{{ item }}"
    state: 'present'
  when: ansible_os_family == 'Debian'
  loop:
    - python3-apt
    - gpg

- include_tasks: sources.yml

- name: 'Install system requirements'
  package:
    name: "{{ item }}"
    state: 'present'
  loop: "{{ pdnsadmin_requirements }}"
