---
- meta: flush_handlers

- name: "Ensure {{ _pdnsadmin_systemd_common_name }} is {{ pdnsadmin_service_state }}"
  service:
    name: "{{ _pdnsadmin_systemd_common_name }}"
    state: "{{ pdnsadmin_service_state }}"
    enabled: "{{ pdnsadmin_service_enabled }}"
