---
- name: Add PowerDNS group
  group:
    name: "{{ pdnsadmin_group }}"
    state: 'present'
    system: true

- name: Add PowerDNS user
  user:
    group: "{{ pdnsadmin_group }}"
    home: "{{ pdnsadmin_user_home }}"
    name: "{{ pdnsadmin_user }}"
    shell: '/sbin/nologin'
    state: 'present'
    system: true

- include_tasks: update_perms.yml
