---
# handlers file for ansible-role_powerdns-admin
- name: 'reload systemd'
  systemd:
    daemon_reload: true
  become: true

- name: 'restart powerdns_admin.socket'
  service:
    name: powerdns_admin.socket
    state: restarted
  become: true

- name: 'restart powerdns_admin.service'
  service:
    name: powerdns_admin.service
    state: restarted
  become: true

- name: 'restart nginx'
  service:
    name: nginx
    state: restarted
  become: true
