---
# handlers file for ansible-role_powerdns-admin
- name: 'reload systemd'
  systemd:
    daemon_reload: true

- name: "restart {{ _pdnsadmin_systemd_common_name }}.socket"
  service:
    name: "{{ _pdnsadmin_systemd_common_name }}.socket"
    state: restarted

- name: "restart {{ _pdnsadmin_systemd_common_name }}.service"
  service:
    name: "{{ _pdnsadmin_systemd_common_name }}.service"
    state: restarted
